function createfigure(xdata1, ydata1, zdata1, X1, Y1, X2, Y2, Y3)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, X1, Y1, X2, Y2, Y3)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 08-Sep-2016 17:18:05

% Create figure
figure1 = figure('Colormap',...
    [0 0 0.5;0 0 0.52;0 0 0.54;0 0 0.56;0 0 0.58;0 0 0.6;0 0 0.62;0 0 0.64;0 0 0.66;0 0 0.68;0 0 0.7;0 0 0.72;0 0 0.74;0 0 0.76;0 0 0.78;0 0 0.8;0 0 0.82;0 0 0.84;0 0 0.86;0 0 0.88;0 0 0.9;0 0 0.92;0 0 0.94;0 0 0.96;0 0 0.98;0.04 0.04 1;0.08 0.08 1;0.12 0.12 1;0.16 0.16 1;0.2 0.2 1;0.24 0.24 1;0.28 0.28 1;0.32 0.32 1;0.36 0.36 1;0.4 0.4 1;0.44 0.44 1;0.48 0.48 1;0.52 0.52 1;0.56 0.56 1;0.6 0.6 1;0.64 0.64 1;0.68 0.68 1;0.72 0.72 1;0.76 0.76 1;0.8 0.8 1;0.84 0.84 1;0.88 0.88 1;0.92 0.92 1;0.96 0.96 1;1 1 1;1 0.96 1;1 0.92 0.96;1 0.88 0.92;1 0.84 0.88;1 0.8 0.84;1 0.76 0.8;1 0.72 0.76;1 0.68 0.72;1 0.64 0.68;1 0.6 0.64;1 0.56 0.6;1 0.52 0.56;1 0.48 0.52;1 0.44 0.48;1 0.4 0.44;1 0.36 0.4;1 0.32 0.36;1 0.28 0.32;1 0.24 0.28;1 0.2 0.24;1 0.16 0.2;1 0.12 0.16;1 0.0800000000000001 0.12;1 0.04 0.08;1 0 0.04;0.98 0 0;0.96 0 0;0.94 0 0;0.92 0 0;0.9 0 0;0.88 0 0;0.86 0 0;0.84 0 0;0.82 0 0;0.8 0 0;0.78 0 0;0.76 0 0;0.74 0 0;0.72 0 0;0.7 0 0;0.68 0 0;0.66 0 0;0.64 0 0;0.62 0 0;0.6 0 0;0.58 0 0;0.56 0 0;0.54 0 0;0.52 0 0;0.5 0 0]);

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create contour
contour(xdata1,ydata1,zdata1,'DisplayName','$Var(OPD)$','Parent',subplot1);

% Create contour
[c1,h1] = contour(xdata1,ydata1,zdata1,'DisplayName','$OPD_{rms}$ from SRA',...
    'Parent',subplot1);

% Create title
title('Mean-removed $\mu_{rms}(\phi)$','FontSize',13.2,...
    'Interpreter','latex');

% Create ylabel
ylabel('$y/\delta$','FontSize',13.2,'Interpreter','latex');

box(subplot1,'on');
grid(subplot1,'on');
axis(subplot1,'tight');
% Set the remaining axes properties
set(subplot1,'BoxStyle','full','CLim',[-0.04 0.04],'FontSize',12,...
    'GridAlpha',0.5,'Layer','top','TickLabelInterpreter','latex','XTickLabel',...
    {'$\pi/2$','$\pi$','$3\pi/2$','$2\pi$','$5\pi/2$','$3\pi$','$7\pi/2$'});
% Create colorbar
colorbar('peer',subplot1,'Position',...
    [0.917647065649799 0.581655480809614 0.0294117647058824 0.340044738011698],...
    'FontSize',10.8);

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y1,'Parent',subplot2,'DisplayName','$Var(OPD)$','LineWidth',3);

% Create plot
plot(X2,Y2,'Parent',subplot2,'DisplayName','$OPD_{rms}$ from SRA',...
    'LineWidth',3,...
    'LineStyle',':',...
    'Color',[1 0 0]);

% Create plot
plot(xdata1,Y3,'Parent',subplot2,'DisplayName','Pressure','LineWidth',3,...
    'LineStyle','--',...
    'Color',[0 1 0]);

% Create xlabel
xlabel('Phase (rad.)','FontSize',13.2);

box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',12,'TickLabelInterpreter','latex','XTickLabel',...
    {'0','$\pi/2$','$\pi$','$3\pi/2$','$2\pi$','$5\pi/2$','$3\pi$','$7\pi/2$','$4\pi$'});
% Create legend
legend1 = legend(subplot2,'show');
set(legend1,'Location','southeast','Interpreter','latex','FontSize',10.8);

